# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kuangzhexi
email: kuangzhexi@126.com
description: > # this means to ignore newlines until "baseurl:"
  写了几年的代码，菜鸟一枚，接触的都是皮毛，搞个blog督促自己沉淀一些东西
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sars715.github.io" # the base hostname & protocol for your site
github_username:  sars715

# Build settings
markdown: kramdown
